use miden_client::account::{AccountId, StorageSlotName};
use miden_client::transaction::{TransactionRequest, TransactionRequestBuilder};
use miden_client::DebugMode;
use miden_client_cli::CliClient;

// v7 contract deployed on Miden testnet v0.15
const CONTRACT_ID: &str = "0x72df3f2c728125716878e6af1422af";

// create_market — proc hash (LE format via Word::to_hex)
const CREATE_HASH: &str =
    "0x901e1be1b97baa9d132a87350ef42624fd06cf0513a8d1cd34e884b43f2b8178";

// Default outcomes for a binary market (outcome-0=YES vs outcome-1=NO).
// Override with --outcomes <N>.
const DEFAULT_OUTCOMES: u64 = 2;
const CLOSE_DELAY_SECS: u64 = 604800; // 7 days (Week 6 markets)

// Slot name generated by #[component_storage] macro: "module::struct::field"
const MARKET_COUNT_SLOT: &str = "weather_market::weather_market_contract::market_count";

// Parses `--outcomes <N>` from argv, defaulting to DEFAULT_OUTCOMES.
fn parse_outcomes_arg() -> u64 {
    let args: Vec<String> = std::env::args().collect();
    args.iter()
        .position(|a| a == "--outcomes")
        .and_then(|i| args.get(i + 1))
        .and_then(|v| v.parse().ok())
        .unwrap_or(DEFAULT_OUTCOMES)
}

fn make_script(close_time: u64, outcomes: u64) -> String {
    // v7: create_market is void (no return), so no drop after call.
    format!(
        r#"begin
    push.{outcomes}   swap.6 drop
    push.{ct}         swap.5 drop
    push.0            swap.4 drop
    push.0            swap.3 drop
    push.0            swap.2 drop
    push.0            swap.1 drop
    call.{hash}
end"#,
        outcomes = outcomes,
        ct       = close_time,
        hash     = CREATE_HASH,
    )
}

// Read the current market_count from on-chain contract storage.
// create_market() uses market_count as the new market_id, then increments it.
// Returns None if storage is not in the local DB (ensure sync_state ran first).
async fn read_market_count(client: &CliClient, contract_id: AccountId) -> Option<u64> {
    let storage = client.get_account_storage(contract_id).await.ok()?;
    let slot_name = StorageSlotName::new(MARKET_COUNT_SLOT).ok()?;
    let word = storage.get_item(&slot_name).ok()?;
    Some(word[0].as_canonical_u64())
}

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    let outcomes = parse_outcomes_arg();

    println!("=== create_market (v7 Weather Market) ===");
    println!("  contract   = {}", CONTRACT_ID);
    println!("  outcomes   = {} (outcome-0=YES vs outcome-1=NO)", outcomes);
    println!("  close_delay = {}s", CLOSE_DELAY_SECS);

    let mut client = CliClient::new(DebugMode::Disabled).await?;

    println!("\nSyncing...");
    let sync = client.sync_state().await?;
    let block_num = sync.block_num;

    // Read current market_count BEFORE creating, so we know what ID the contract will assign.
    // The contract executes: new_id = market_count; market_count += 1.
    let contract_id = AccountId::from_hex(CONTRACT_ID)?;
    let expected_market_id: Option<u64> = read_market_count(&client, contract_id).await;
    match expected_market_id {
        Some(n) => {
            println!("  market_count (on-chain) = {n}");
            println!("  → this call will create market_id = {n}");
        }
        None => {
            println!("  [warn] could not read market_count from chain storage");
            println!("  → market_id unknown; check contract state manually after TX");
        }
    }

    let block_header = client
        .get_block_header_by_num(block_num)
        .await?
        .ok_or("block header not found")?;
    let block_ts   = block_header.0.timestamp() as u64;
    let close_time = block_ts + CLOSE_DELAY_SECS;

    println!("  block_num  = {}", block_num);
    println!("  block_ts   = {}", block_ts);
    println!("  close_time = {} (block_ts + {}s)", close_time, CLOSE_DELAY_SECS);

    let script = make_script(close_time, outcomes);
    println!("\nScript:\n{}", script);

    println!("Compiling create_market script...");
    let tx_script = client.code_builder().compile_tx_script(&script)?;

    let tx_request: TransactionRequest = TransactionRequestBuilder::new()
        .custom_script(tx_script)
        .build()?;

    println!("Submitting create_market transaction...");
    let tx_id = client.submit_new_transaction(contract_id, tx_request).await?;

    println!("\n=== create_market TX submitted ===");
    println!("  TX hash    = {:?}", tx_id);
    match expected_market_id {
        Some(n) => println!("  market_id  = {n}  (market_count was {n} before this call)"),
        None    => println!("  market_id  = <unknown — check market_count on-chain>"),
    }
    println!("  close_time = {}", close_time);
    println!("  outcomes   = {}", outcomes);
    println!("\n*** SAVE close_time={} for settle_market ***", close_time);
    let id_str = expected_market_id
        .map(|n| n.to_string())
        .unwrap_or_else(|| "<market_id>".into());
    println!("\nNext: submit-place-bet {id_str} 0 100 42  (outcome=0=YES, amount=100, secret=42)");

    Ok(())
}
