"weather_market::weather_market_contract::initialized" = "0"
"weather_market::weather_market_contract::market_count" = "0"
"weather_market::weather_market_contract::oracle_pubkey_hash" = ["0", "0", "0", "0"]
