[package]
name = "submit-place-bet"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "submit-place-bet"
path = "src/main.rs"

[dependencies]
miden-client-cli = "0.15"
miden-client = { version = "0.15", features = ["std"] }
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
miden-crypto = "0.25"
